version: '3.8'

services:
  server:
    build: .
    ports:
      - "${SERVER_PORT}:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ${SERVICE_ACCOUNT_FILE}:/app/credentials.json
    env_file:
      - .env
